name: Push ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Auth AWS
        env: 
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
        run: |
           aws configure set aws_access_key_id $AWS_ACCESS_KEY
           aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
           aws configure set default.region us-east-1
        
      - name: Push To GCR
        run: |
          docker login -u AWS -p $(aws ecr get-login-password --region us-east-1) 508476262833.dkr.ecr.us-east-1.amazonaws.com
          docker build --build-arg MONGODB_ADDON_URI_ARG=${{ secrets.MONGODB_ADDON_URI }} -t meteorhiring:latest .
          docker tag meteorhiring:latest 508476262833.dkr.ecr.us-east-1.amazonaws.com/meteorhiring:latest
          docker push 508476262833.dkr.ecr.us-east-1.amazonaws.com/meteorhiring:latest
